# サイト基本情報
title: "mikann-260"
description: "mikann-260のサイトです。"
lang: "ja"
timezone: "Asia/Tokyo"

# PWA
pwa:
  enabled: false
  title: "mikann-260"

# URL設定
url: "https://mikann-260.github.io"
baseurl: ""

# Google Search Console
google_search_console:
  verification: "YXWdwa2HAg_VdsD4uW7mkdOaZ8CtlTOaGcZrMvWzfA0"

# Cloudflare Web Analysis
cloudflare:
  token: "2ef183f9463a46c8a32bc608fec54eaf"

# 作成者
author:
  name: "mikann-260"

# ビルド設定
source: "docs"

# プラグイン
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
